global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

scrape_configs:
  # Prometheus собирает метрики о самом себе
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Spring Boot Actuator метрики для service-one
  - job_name: 'service-one'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['service-one:8080']
    scrape_timeout: 10s

  # Spring Boot Actuator метрики для service-two (если добавите туда Prometheus)
  - job_name: 'service-two'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['service-two:8081']
    scrape_timeout: 10s

  # API Gateway метрики (если добавите туда Prometheus)
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['api-gateway:8000']
    scrape_timeout: 10s

  # Системные метрики с node-exporter (опционально)
  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093